[package]
name = "laserbeam"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
